date-format: MMMM d, yyyy
decimal-format: "###,###"

wiki:
  domain: "wiki.crafters.one"
  script-path: "/mediawiki"
  protocol: "https://"
  credentials:
    username: ""
    password: ""

debug: false